#include <iostream>
#include <string>

using namespace std;

string lang(int, int);

string lang(int langID, int msgID)
{
	string LANG[47];
	switch (langID)
	{
		case 1: // English
			LANG[0] = "Nothing";
			LANG[1] = "Pair";
			LANG[2] = "Two Pair";
			LANG[3] = "Three-of-a-kind";
			LANG[4] = "Straight";
			LANG[5] = "Flush";
			LANG[6] = "Full House";
			LANG[7] = "Four-of-a-kind";
			LANG[8] = "Straight Flush";
			LANG[9] = "Royal Flush";
			LANG[10] = "Round";
			LANG[11] = "Bank Roll";
			LANG[12] = "How much would you like to bet (0 to quit)?";
			LANG[13] = "Final Bank Roll";
			LANG[14] = "Thank you for playing Video Poker";
			LANG[15] = "Bet";
			LANG[16] = "Here are the cards in your hand";
			LANG[17] = "You must hold at least";
			LANG[18] = "card";
			LANG[19] = "Type in the number of the card you wish to hold/discard (0 to continue)";
			LANG[20] = "You have";
			LANG[21] = "You get";
			LANG[22] = " back";
			LANG[23] = "You have lost all your money";
			LANG[24] = "Thank you for playing Video Poker.";
			LANG[25] = "Game Statistics";
			LANG[26] = "Money ";
			LANG[27] = "Lost";
			LANG[28] = "Gained";
			LANG[29] = "Number of Rounds";
			LANG[30] = "Win/Loss Ratio";
			LANG[31] = "Infinity";
			LANG[32] = "Highest Win Streak";
			LANG[33] = "Highest Loss Streak";
			LANG[34] = "Total Time Spent";
			LANG[35] = "Total Number of Cards Dealt";
			LANG[36] = "Average Number of Cards Discarded";
			LANG[37] = "Highest Bank Roll";
			LANG[38] = "Lowest Bank Roll";
			LANG[39] = "Average Bet";
			LANG[40] = "Biggest Bet";
			LANG[41] = "Biggest Gain";
			LANG[42] = "Biggest Loss";
			LANG[43] = "Number of ";
			LANG[44] = "minute";
			LANG[45] = "second";
			LANG[46] = "Press the \"any\" key to continue . . . ";
			break;
		case 2: // French
			LANG[0] = "Rien";
			LANG[1] = "Paire";
			LANG[2] = "Double Paire";
			LANG[3] = "Brelan";
			LANG[4] = "Suite";
			LANG[5] = "Couleur";
			LANG[6] = "Full";
			LANG[7] = "Carr\x82";
			LANG[8] = "Quinte Flush";
			LANG[9] = "Quinte Flush Royale";
			LANG[10] = "Tour";
			LANG[11] = "Balance";
			LANG[12] = "Combien voulez-vous parier (0 pour quitter)?";
			LANG[13] = "Balance Finale";
			LANG[14] = "Merci d'avoir jou\x82 \x85 Video Poker";
			LANG[15] = "Pari";
			LANG[16] = "Voici les cartes dans votre main";
			LANG[17] = "Vous devez garder au moins";
			LANG[18] = "carte";
			LANG[19] = "Tapez le num\x82ro de la carte que vous voulez garder/jeter (0 pour continuer)";
			LANG[20] = "Vous avez";
			LANG[21] = "Vous recevez";
			LANG[22] = " en retour";
			LANG[23] = "Vous avez perdu tout votre argent";
			LANG[24] = "Merci d'avoir jou\x82 \x85 Video Poker.";
			LANG[25] = "Statistique du jeu";
			LANG[26] = "Argent ";
			LANG[27] = "perdu";
			LANG[28] = "gagn\x82";
			LANG[29] = "Nombre de tours";
			LANG[30] = "Ratio victoire/perte";
			LANG[31] = "Infini";
			LANG[32] = "S\x82rie de victoires la plus longue";
			LANG[33] = "S\x82rie de pertes la plus longue";
			LANG[34] = "Temps total";
			LANG[35] = "Nombre total de cartes distribu\x82\x65s";
			LANG[36] = "Nombre de cartes jet\x82\x65s en moyenne";
			LANG[37] = "Balance la plus haute";
			LANG[38] = "Balance la plus basse";
			LANG[39] = "Pari moyen";
			LANG[40] = "Plus grand pari";
			LANG[41] = "Plus gros gain";
			LANG[42] = "Plus grosse perte";
			LANG[43] = "Nombre de ";
			LANG[44] = "minute";
			LANG[45] = "seconde";
			LANG[46] = "Appuyez sur une touche pour continuer... ";
			break;
		case 3: // Spanish
			LANG[0] = "Nada";
			LANG[1] = "Pareja";
			LANG[2] = "Dobles Parejas";
			LANG[3] = "Tr\xA1o";
			LANG[4] = "Escalera";
			LANG[5] = "Color";
			LANG[6] = "Full";
			LANG[7] = "P\xA2ker";
			LANG[8] = "Escalera de color";
			LANG[9] = "Escalera real";
			LANG[10] = "Ronda";
			LANG[11] = "Balanza";
			LANG[12] = "\xA8 Cu\xA0nto le quiere apostar (0 para salir) ?";
			LANG[13] = "Balanza Final";
			LANG[14] = "Gracias por jugar Video Poker";
			LANG[15] = "Apuesta";
			LANG[16] = "Aqu\xA1 est\xA0n las cartas en la mano";
			LANG[17] = "Usted necesita conservar";
			LANG[18] = "carta";
			LANG[19] = "N\xA3mero de la carta que desea conservar/descartar (0 para continuar)";
			LANG[20] = "Usted tiene";
			LANG[21] = "Usted recibe";
			LANG[22] = " a cambio";
			LANG[23] = "Ha perdido todo su dinero";
			LANG[24] = "Gracias por jugar Video Poker.";
			LANG[25] = "Estad\xA1sticas de juego";
			LANG[26] = "Dinero ";
			LANG[27] = "perdido";
			LANG[28] = "ganado";
			LANG[29] = "N\xA3mero de vueltas";
			LANG[30] = "Relaci\xA2n de ganar/p\x82rdida";
			LANG[31] = "Infinita";
			LANG[32] = "Racha ganadora m\xA0s larga";
			LANG[33] = "Serie de p\x82rdidas m\xA0s larga";
			LANG[34] = "Tiempo total";
			LANG[35] = "N\xA3mero total de tarjetas distribuidas";
			LANG[36] = "N\xA3mero medio de cartas descartadas";
			LANG[37] = "Balanza m\xA0s alta";
			LANG[38] = "Balanza m\xA0s baja";
			LANG[39] = "Promedio de apuesta";
			LANG[40] = "Apuesta m\xA0s alta";
			LANG[41] = "Ganancia m\xA0s alta";
			LANG[42] = "P\x82rdida m\xA0s alta";
			LANG[43] = "N\xA3mero de ";
			LANG[44] = "minuto";
			LANG[45] = "segundo";
			LANG[46] = "Presione una tecla para continuar... ";
			break;
	}
	return LANG[msgID];
}